In [39]:
# Bibliotecas
import pandas as pd
import geopandas as gpd 
import numpy as np
import fiona 
from tqdm.notebook import tqdm
import time
from pathlib import Path

In [40]:
# Ajuste na exibição do Pandas
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 200)
pd.set_option('display.float_format', '{:.2f}'.format)

In [41]:
# Importando Dados
GDB_PATH = r'C:\Users\brenn\OneDrive\Documentos\Projetos\Python\Viabilidade_eletropostos\data\raw\mapa_distribuicao\CPFL_Paulista_63_2024-12-31_V11_20250731-1036.gdb'
NOME_DIST = 'CPFL_PAULISTA'

# Verificar se o arquivo existe
assert Path(GDB_PATH).exists(), f"Arquivo não encontrado: {GDB_PATH}"
print(f"✓ BDGD encontrada: {GDB_PATH}")
print(f"✓ Distribuidora: {NOME_DIST}")

✓ BDGD encontrada: C:\Users\brenn\OneDrive\Documentos\Projetos\Python\Viabilidade_eletropostos\data\raw\mapa_distribuicao\CPFL_Paulista_63_2024-12-31_V11_20250731-1036.gdb
✓ Distribuidora: CPFL_PAULISTA

In [42]:
# Listagem de tabelas e camadas do .gdb
camadas = fiona.listlayers(GDB_PATH)
print(f'Total de Camadas: {len(camadas)}\n')
for c in sorted(camadas):
    print(f"  - {c}")

Total de Camadas: 43

  - ARAT
  - BAR
  - BASE
  - BAY
  - BE
  - CONJ
  - CRVCRG
  - CTAT
  - CTMT
  - EP
  - EQCR
  - EQME
  - EQRE
  - EQSE
  - EQTRAT
  - EQTRM
  - EQTRMT
  - PIP
  - PNT
  - PONNOT
  - PT
  - RAMLIG
  - SEGCON
  - SSDAT
  - SSDBT
  - SSDMT
  - SUB
  - UCAT_tab
  - UCBT_tab
  - UCMT_tab
  - UGAT_tab
  - UGBT_tab
  - UGMT_tab
  - UNCRAT
  - UNCRBT
  - UNCRMT
  - UNREAT
  - UNREMT
  - UNSEAT
  - UNSEBT
  - UNSEMT
  - UNTRAT
  - UNTRMT

In [43]:
# Carregando CTMT
print("Carregando CTMT...")
ctmt = gpd.read_file(GDB_PATH, layer="CTMT")
print(f"✓ {len(ctmt):,} alimentadores carregados\n")

print("Colunas disponíveis:")
print(ctmt.columns.tolist())

print("\nPrimeiras 5 linhas:")
display(ctmt.head())

print("\nTipos de dados:")
print(ctmt.dtypes)

Carregando CTMT...
✓ 1,636 alimentadores carregados

Colunas disponíveis:
['COD_ID', 'NOME', 'BARR', 'SUB', 'PAC_INI', 'TEN_NOM', 'TEN_OPE', 'ATIP', 'RECONFIG', 'DIST', 'UNI_TR_AT', 'ENE_01', 'ENE_02', 'ENE_03', 'ENE_04', 'ENE_05', 'ENE_06', 'ENE_07', 'ENE_08', 'ENE_09', 'ENE_10', 'ENE_11', 'ENE_12', 'PERD_A3a', 'PERD_A4', 'PERD_B', 'PERD_MED', 'PERD_A3aA4', 'PERD_A3a_B', 'PERD_A4A3a', 'PERD_A4_B', 'PERD_B_A3a', 'PERD_B_A4', 'PNTMT_01', 'PNTMT_02', 'PNTMT_03', 'PNTMT_04', 'PNTMT_05', 'PNTMT_06', 'PNTMT_07', 'PNTMT_08', 'PNTMT_09', 'PNTMT_10', 'PNTMT_11', 'PNTMT_12', 'PNTBT_01', 'PNTBT_02', 'PNTBT_03', 'PNTBT_04', 'PNTBT_05', 'PNTBT_06', 'PNTBT_07', 'PNTBT_08', 'PNTBT_09', 'PNTBT_10', 'PNTBT_11', 'PNTBT_12', 'DESCR']

Primeiras 5 linhas:

,COD_ID,NOME,BARR,SUB,PAC_INI,TEN_NOM,TEN_OPE,ATIP,RECONFIG,DIST,UNI_TR_AT,ENE_01,ENE_02,ENE_03,ENE_04,ENE_05,ENE_06,ENE_07,ENE_08,ENE_09,ENE_10,ENE_11,ENE_12,PERD_A3a,PERD_A4,...,PNTMT_01,PNTMT_02,PNTMT_03,PNTMT_04,PNTMT_05,PNTMT_06,PNTMT_07,PNTMT_08,PNTMT_09,PNTMT_10,PNTMT_11,PNTMT_12,PNTBT_01,PNTBT_02,PNTBT_03,PNTBT_04,PNTBT_05,PNTBT_06,PNTBT_07,PNTBT_08,PNTBT_09,PNTBT_10,PNTBT_11,PNTBT_12,DESCR
0,ITI02,ITI02,,ITI,MT_ITI02_464,49,1.00,0,0,63,29017897,1198075.55,1134523.87,1234812.17,1143774.67,1104420.15,976100.07,989835.80,991465.14,1115412.35,1155056.18,1113781.13,1119272.50,0.00,56652.61,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,100524.34,97895.82,125506.73,109484.14,111963.54,81737.62,84744.19,52446.72,137003.78,164957.96,146713.87,104411.61,
1,ITI01,ITI01,,ITI,MT_ITI01_465,49,1.00,0,0,63,29017897,1068536.20,1005101.96,1115193.65,1004508.82,984362.02,853349.13,859368.64,896022.14,1016167.30,1087296.11,1047261.04,1077763.59,0.00,88191.41,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,91739.22,88293.34,115434.77,97350.63,101120.05,72280.24,74483.22,46271.36,120921.88,146405.63,130000.49,96528.40,
2,PNE11,PNE11,,PNE,MT_PNE11_728,41,1.04,0,0,63,29018224,2670993.49,2493467.61,2692215.31,2520729.89,2470162.02,2194058.50,2193441.93,2179548.08,2444260.90,2648197.61,2488797.88,2549665.31,0.00,196387.16,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,59029.35,57890.17,73731.42,65256.26,69109.66,53385.37,55675.65,34492.67,86678.40,104872.00,94643.41,68527.47,
3,TAQ12,TAQ12,,TAQ,MT_TAQ12_917,41,1.04,0,0,63,29018416,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,
4,RIB31,RIB31,,RIB,MT_RIB31_1146,72,1.03,0,0,63,149650235,4938859.36,4427869.32,4992142.82,4619729.66,4617249.22,3972520.07,4388241.13,4410221.18,4697211.26,4999827.64,4785737.32,5000668.63,3246551.87,44342.84,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,

Tipos de dados:
COD_ID            str
NOME              str
BARR              str
SUB               str
PAC_INI           str
TEN_NOM           str
TEN_OPE       float64
ATIP            int32
RECONFIG        int32
DIST            int32
UNI_TR_AT         str
ENE_01        float64
ENE_02        float64
ENE_03        float64
ENE_04        float64
ENE_05        float64
ENE_06        float64
ENE_07        float64
ENE_08        float64
ENE_09        float64
ENE_10        float64
ENE_11        float64
ENE_12        float64
PERD_A3a      float64
PERD_A4       float64
PERD_B        float64
PERD_MED      float64
PERD_A3aA4    float64
PERD_A3a_B    float64
PERD_A4A3a    float64
PERD_A4_B     float64
PERD_B_A3a    float64
PERD_B_A4     float64
PNTMT_01      float64
PNTMT_02      float64
PNTMT_03      float64
PNTMT_04      float64
PNTMT_05      float64
PNTMT_06      float64
PNTMT_07      float64
PNTMT_08      float64
PNTMT_09      float64
PNTMT_10      float64
PNTMT_11      float64
PNTMT_12      float64
PNTBT_01      float64
PNTBT_02      float64
PNTBT_03      float64
PNTBT_04      float64
PNTBT_05      float64
PNTBT_06      float64
PNTBT_07      float64
PNTBT_08      float64
PNTBT_09      float64
PNTBT_10      float64
PNTBT_11      float64
PNTBT_12      float64
DESCR             str
dtype: object

In [44]:
# Decodificando Tensão Nominal (Código DDA -> kV): Tabela DDA da ANEEL
DDA_TENSAO_KV = {
    '0': None,
    '1': 0.110,
    '2': 0.115,
    '3': 0.120,
    '4': 0.121,
    '5': 0.125,
    '6': 0.127,
    '7': 0.208,
    '8': 0.216,
    '9': 0.2165,
    '10': 0.220,
    '11': 0.230,
    '12': 0.231,
    '13': 0.240,
    '14': 0.254,
    '15': 0.380,
    '16': 0.400,
    '17': 0.440,
    '18': 0.480,
    '19': 0.500,
    '20': 0.600,
    '21': 0.750,
    '22': 1.0,
    '23': 2.2,
    '24': 3.2,
    '25': 3.6,
    '26': 3.785,
    '27': 3.8,
    '28': 3.848,
    '29': 3.985,
    '30': 4.16,
    '31': 4.2,
    '32': 4.207,
    '33': 4.368,
    '34': 4.56,
    '35': 5.0,
    '36': 6.0,
    '37': 6.6,
    '38': 6.93,
    '39': 7.96,
    '40': 8.67,
    '41': 11.4,
    '42': 11.9,
    '43': 12.0,
    '44': 12.6,
    '45': 12.7,
    '46': 13.2,
    '47': 13.337,
    '48': 13.53,
    '49': 13.8,
    '50': 13.86,
    '51': 14.14,
    '52': 14.19,
    '53': 14.4,
    '54': 14.835,
    '55': 15.0,
    '56': 15.2,
    '57': 19.053,
    '58': 19.919,
    '59': 21.0,
    '60': 21.5,
    '61': 22.0,
    '62': 23.0,
    '63': 23.1,
    '64': 23.827,
    '65': 24.0,
    '66': 24.2,
    '67': 25.0,
    '68': 25.8,
    '69': 27.0,
    '70': 30.0,
    '71': 33.0,
    '72': 34.5,
    '73': 36.0,
    '74': 38.0,
    '75': 40.0,
    '76': 44.0,
    '77': 45.0,
    '78': 45.4,
    '79': 48.0,
    '80': 60.0,
    '81': 66.0,
    '82': 69.0,
    '83': 72.5,
    '84': 88.0,
    '85': 88.2,
    '86': 92.0,
    '87': 100.0,
    '88': 120.0,
    '89': 121.0,
    '90': 123.0,
    '91': 131.6,
    '92': 131.63,
    '93': 131.635,
    '94': 138.0,
    '95': 145.0,
    '96': 230.0,
    '97': 345.0,
    '98': 500.0,
    '99': 750.0,
    '100': 1000.0,
    '101': 245.0,
    '102': 550.0
}

# Mostra primeiro quais códigos existem na BDGD
print("Códigos TEN_NOM presentes na CTMT:")
print(ctmt['TEN_NOM'].value_counts().sort_index())

Códigos TEN_NOM presentes na CTMT:
TEN_NOM
41    610
42    168
46    440
49    393
72     24
77      1
Name: count, dtype: int64

In [45]:
# Aplicando Tradução
ctmt['ten_nom_kv'] = ctmt['TEN_NOM'].map(DDA_TENSAO_KV)

# Verifica se algum código ficou sem tradução
nao_mapeados = ctmt[ctmt['ten_nom_kv'].isna()]['TEN_NOM'].unique()
if len(nao_mapeados) > 0:
    print(f"⚠️ Códigos não mapeados: {nao_mapeados}")
    print("Adicione-os ao dicionário DDA_TENSAO_KV e re-execute.")
else:
    print("✓ Todos os códigos foram traduzidos com sucesso.")

print("\nDistribuição de tensões:")
print(ctmt['ten_nom_kv'].value_counts().sort_index())

✓ Todos os códigos foram traduzidos com sucesso.

Distribuição de tensões:
ten_nom_kv
11.40    610
11.90    168
13.20    440
13.80    393
34.50     24
45.00      1
Name: count, dtype: int64

In [46]:
# Carrega SSDMT e calcula comprimento por CTMT
print("Carregando SSDMT (segmentos de média tensão)...")
print("(pode levar 1-3 min em distribuidoras médias)\n")

# Carrega só as colunas necessárias para economizar memória
ssdmt = gpd.read_file(
    GDB_PATH,
    layer="SSDMT",
    columns=['CTMT', 'COMP', 'geometry']
)
print(f"✓ {len(ssdmt):,} segmentos de MT")
print(f"✓ CRS: {ssdmt.crs}")
print(f"\nColunas: {ssdmt.columns.tolist()}")
print(f"\nAmostra:")
display(ssdmt.head())

Carregando SSDMT (segmentos de média tensão)...
(pode levar 1-3 min em distribuidoras médias)

✓ 1,758,519 segmentos de MT
✓ CRS: EPSG:4674

Colunas: ['CTMT', 'COMP', 'geometry']

Amostra:

    CTMT   COMP                                           geometry
0  AUX33  91.80  MULTILINESTRING ((-48.21492 -23.01894, -48.215...
1  AUX33  87.33  MULTILINESTRING ((-48.30963 -23.24264, -48.308...
2  AUX33  98.28  MULTILINESTRING ((-48.15688 -22.98782, -48.156...
3  AUX33 100.91  MULTILINESTRING ((-48.34326 -23.2401, -48.3437...
4  AUX33 119.35  MULTILINESTRING ((-48.31848 -23.25149, -48.318...

In [47]:
# %% [Célula 5b] — Calcula comprimento total por alimentador
if 'COMP' in ssdmt.columns and ssdmt['COMP'].notna().any():
    print("Usando coluna COMP da BDGD (em metros)")
    ssdmt['_comp_m'] = ssdmt['COMP'].astype(float)
else:
    print("Coluna COMP indisponível — calculando da geometria")
    # Reprojeta para SIRGAS 2000 / Brasil Polyconic (EPSG:5880) — métrico
    ssdmt_metric = ssdmt.to_crs(epsg=5880)
    ssdmt['_comp_m'] = ssdmt_metric.geometry.length

# Agrega por alimentador
comp_por_ctmt = ssdmt.groupby('CTMT').agg(
    comp_total_km=('_comp_m', lambda x: x.sum() / 1000),
    n_segmentos=('_comp_m', 'count')
).reset_index()

print(f"\n✓ {len(comp_por_ctmt):,} alimentadores com geometria")
print("\nDistribuição do comprimento:")
print(comp_por_ctmt['comp_total_km'].describe().round(2))
print("\nAmostra:")
display(comp_por_ctmt.head())

Usando coluna COMP da BDGD (em metros)

✓ 1,638 alimentadores com geometria

Distribuição do comprimento:
count   1638.00
mean      55.46
std       85.39
min        0.00
25%       10.95
50%       22.04
75%       64.92
max      979.86
Name: comp_total_km, dtype: float64

Amostra:

    CTMT  comp_total_km  n_segmentos
0  ABR07          35.17          655
1  ABR08         164.28         2583
2  ABR09          40.53         1245
3  ABR10          25.78          821
4  ABR11          26.88          754

In [48]:
# UCBT: a tabela mais pesada — milhões de linhas
print("Carregando UCBT (consumidores de baixa tensão)...")
print("(pode demorar 2-10 min)\n")

# CRÍTICO: carregar SÓ as colunas necessárias
# Se sua versão da BDGD tem nomes diferentes, ajuste aqui
cols_ucbt_essenciais = ['COD_ID', 'CTMT', 'CLAS_SUB']  # mínimo para contagem
cols_ucbt_energia = [f'ENE_{i:02d}' for i in range(1, 13)]  # ENE_01 a ENE_12

# Tenta carregar com energia primeiro
try:
    ucbt = gpd.read_file(
        GDB_PATH, layer="UCBT_tab",  # ⚠️ pode ser "UCBT" sem _tab — ajuste!
        columns=cols_ucbt_essenciais + cols_ucbt_energia
    )
except Exception as e:
    print(f"Tentativa com _tab falhou: {e}")
    print("Tentando UCBT sem sufixo...")
    ucbt = gpd.read_file(
        GDB_PATH, layer="UCBT",
        columns=cols_ucbt_essenciais + cols_ucbt_energia
    )

print(f"✓ {len(ucbt):,} unidades consumidoras BT")
print(f"\nColunas: {ucbt.columns.tolist()}")
print(f"\nAmostra:")
display(ucbt.head())

Carregando UCBT (consumidores de baixa tensão)...
(pode demorar 2-10 min)

✓ 5,113,963 unidades consumidoras BT

Colunas: ['CTMT', 'CLAS_SUB', 'ENE_01', 'ENE_02', 'ENE_03', 'ENE_04', 'ENE_05', 'ENE_06', 'ENE_07', 'ENE_08', 'ENE_09', 'ENE_10', 'ENE_11', 'ENE_12', 'COD_ID']

Amostra:

    CTMT CLAS_SUB  ENE_01  ENE_02  ENE_03  ENE_04  ENE_05  ENE_06  ENE_07  ENE_08  ENE_09  ENE_10  ENE_11  ENE_12                                             COD_ID
0  PGI10      RE1    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  03982b617155a7742d9d2bd802a21b4e32e2fa71deb5e0...
1  PGI10      RE1    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  2b0b57fcf71384c32da60dee9b42bc37476041fc18df07...
2  PGI10      RE1    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  9f6c062bb8a402b21d8f31e0eb1c9864ddd21fed7d251a...
3  PGI10      RE1    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  5c20ecbfd981d9a990f99eac2f4d0f25c0a3fcb9d0c81d...
4  PGI08      RE1    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00  392e9a7283252626ab5ecff2388e315206ec5e35f6ba3c...

In [49]:
# Conta UCBT por alimentador, removendo "0" (sem associação)
# Filtra zeros e nulos
ucbt_validas = ucbt[
    (ucbt['CTMT'].notna()) &
    (ucbt['CTMT'] != '0') &
    (ucbt['CTMT'] != 0)
].copy()

print(f"UCBT válidas (com CTMT atribuído): {len(ucbt_validas):,}")
print(f"UCBT descartadas (CTMT=0 ou nulo): {len(ucbt) - len(ucbt_validas):,}\n")

# Conta por alimentador
n_ucbt_por_ctmt = ucbt_validas.groupby('CTMT').size().reset_index(name='n_ucbt')

print(f"Alimentadores com UCBT: {len(n_ucbt_por_ctmt):,}")
print(f"\nDistribuição:")
print(n_ucbt_por_ctmt['n_ucbt'].describe().round(0))
print(f"\nAmostra:")
display(n_ucbt_por_ctmt.head())

UCBT válidas (com CTMT atribuído): 5,113,963
UCBT descartadas (CTMT=0 ou nulo): 0

Alimentadores com UCBT: 1,532

Distribuição:
count    1532.00
mean     3338.00
std      2161.00
min         1.00
25%      1612.00
50%      3252.00
75%      4870.00
max     14236.00
Name: n_ucbt, dtype: float64

Amostra:

    CTMT  n_ucbt
0  ABR07     767
1  ABR08    6189
2  ABR09    6329
3  ABR10    3042
4  ABR11    3747

In [50]:
# UCMT (consumidores MT — comércios médios, indústrias)
print("Carregando UCMT...")
try:
    ucmt = gpd.read_file(
        GDB_PATH, layer="UCMT_tab",
        columns=cols_ucbt_essenciais + cols_ucbt_energia
    )
except:
    ucmt = gpd.read_file(
        GDB_PATH, layer="UCMT",
        columns=cols_ucbt_essenciais + cols_ucbt_energia
    )

print(f"✓ {len(ucmt):,} unidades consumidoras MT\n")

ucmt_validas = ucmt[
    (ucmt['CTMT'].notna()) &
    (ucmt['CTMT'] != '0') &
    (ucmt['CTMT'] != 0)
].copy()

n_ucmt_por_ctmt = ucmt_validas.groupby('CTMT').size().reset_index(name='n_ucmt')

print(f"Alimentadores com UCMT: {len(n_ucmt_por_ctmt):,}")
display(n_ucmt_por_ctmt.head())

Carregando UCMT...
✓ 28,734 unidades consumidoras MT

Alimentadores com UCMT: 1,534

    CTMT  n_ucmt
0  ABR07       6
1  ABR08      15
2  ABR09      23
3  ABR10      37
4  ABR11      13

In [51]:
# Calcula demanda média a partir das energias mensais
# Lógica: ENE_XX está em kWh por mês.
# Soma 12 meses → energia anual (kWh/ano)
# Divide por 8760 horas/ano → potência média (kW)

cols_ene_disp_bt = [c for c in cols_ucbt_energia if c in ucbt_validas.columns]
print(f"Colunas de energia BT disponíveis: {cols_ene_disp_bt}")

if cols_ene_disp_bt:
    # Soma anual por UC, depois agrega por alimentador
    ucbt_validas['_ene_anual_kwh'] = ucbt_validas[cols_ene_disp_bt].sum(axis=1)
    ucbt_validas['_dem_med_kw'] = ucbt_validas['_ene_anual_kwh'] / 8760

    dem_bt = ucbt_validas.groupby('CTMT')['_dem_med_kw'].sum().reset_index(
        name='dem_med_ucbt_kw'
    )
else:
    print("⚠️ Sem colunas de energia em UCBT — pulando")
    dem_bt = pd.DataFrame({'CTMT': [], 'dem_med_ucbt_kw': []})

# Mesmo para UCMT
cols_ene_disp_mt = [c for c in cols_ucbt_energia if c in ucmt_validas.columns]
if cols_ene_disp_mt:
    ucmt_validas['_ene_anual_kwh'] = ucmt_validas[cols_ene_disp_mt].sum(axis=1)
    ucmt_validas['_dem_med_kw'] = ucmt_validas['_ene_anual_kwh'] / 8760
    dem_mt = ucmt_validas.groupby('CTMT')['_dem_med_kw'].sum().reset_index(
        name='dem_med_ucmt_kw'
    )
else:
    dem_mt = pd.DataFrame({'CTMT': [], 'dem_med_ucmt_kw': []})

# Junta os dois
demanda = dem_bt.merge(dem_mt, on='CTMT', how='outer').fillna(0)
demanda['dem_total_kw'] = demanda['dem_med_ucbt_kw'] + demanda['dem_med_ucmt_kw']

print(f"\nDemanda calculada para {len(demanda):,} alimentadores")
print("\nEstatísticas (kW médio):")
print(demanda[['dem_med_ucbt_kw', 'dem_med_ucmt_kw', 'dem_total_kw']].describe().round(0))
display(demanda.head())

Colunas de energia BT disponíveis: ['ENE_01', 'ENE_02', 'ENE_03', 'ENE_04', 'ENE_05', 'ENE_06', 'ENE_07', 'ENE_08', 'ENE_09', 'ENE_10', 'ENE_11', 'ENE_12']

Demanda calculada para 1,558 alimentadores

Estatísticas (kW médio):
       dem_med_ucbt_kw  dem_med_ucmt_kw  dem_total_kw
count          1558.00          1558.00       1558.00
mean           1177.00           875.00       2052.00
std             706.00           905.00       1058.00
min               0.00             0.00          0.00
25%             665.00           257.00       1377.00
50%            1190.00           573.00       1955.00
75%            1642.00          1172.00       2633.00
max            4684.00          6326.00       7258.00

    CTMT  dem_med_ucbt_kw  dem_med_ucmt_kw  dem_total_kw
0  ABR07           244.04           900.86       1144.91
1  ABR08          1760.18           810.91       2571.10
2  ABR09          2046.47           329.92       2376.40
3  ABR10           853.04          1122.74       1975.78
4  ABR11           892.79           755.27       1648.06

In [52]:
# %% [Célula 9 — VERSÃO CORRIGIDA] Mapeamento de CLAS_SUB alfanumérico

# Tabela DDA-ANEEL: prefixos de CLAS_SUB → classe principal (8 categorias)
# Fonte: Manual de Instruções da BDGD, Anexo I (DDA)
DDA_PREFIXO_CLASSE = {
    'RE': 'residencial',     # RE1, RE2, RE3, RE4, RE5
    'CO': 'comercial',       # CO1 a CO9
    'IN': 'industrial',      # IN
    'RU': 'rural',           # RU1, RU1A, RU1B, RU2, RU3, RU5, RU7, RU8
    'PP': 'poder_publico',   # PP1, PP2, PP3
    'IP': 'iluminacao_publica',  # IP
    'SP': 'servico_publico', # SP1, SP2
    'CP': 'consumo_proprio', # CPR, CPRVE
}

# Verifica primeiro: existe a coluna CLAS_SUB? E como ela está preenchida?
print("Tipo da coluna CLAS_SUB:", ucbt_validas['CLAS_SUB'].dtype)
print("\nPrimeiros 10 valores únicos:")
print(ucbt_validas['CLAS_SUB'].value_counts().head(10))

# Aplica o mapeamento — pega os 2 primeiros caracteres como prefixo
# .astype(str) garante que mesmo se vier numérico ou misto, vire string
ucbt_validas['_prefixo'] = ucbt_validas['CLAS_SUB'].astype(str).str[:2].str.upper()

# Mapeia para a classe principal
ucbt_validas['_classe'] = ucbt_validas['_prefixo'].map(DDA_PREFIXO_CLASSE)

# Sanity check
nao_mapeados = ucbt_validas[ucbt_validas['_classe'].isna()]['CLAS_SUB'].value_counts()
if len(nao_mapeados) > 0:
    print(f"\n⚠️ Códigos NÃO mapeados ({len(nao_mapeados)} tipos):")
    print(nao_mapeados.head(10))
    print("→ Esses caem em 'outros' no pivot")
else:
    print("\n✓ Todos os CLAS_SUB foram mapeados com sucesso")

# Preenche os não mapeados com 'outros'
ucbt_validas['_classe'] = ucbt_validas['_classe'].fillna('outros')

print("\n--- Distribuição final por classe ---")
print(ucbt_validas['_classe'].value_counts())
print(f"\nTotal de UCs: {len(ucbt_validas):,}")

Tipo da coluna CLAS_SUB: str

Primeiros 10 valores únicos:
CLAS_SUB
RE1    4358194
RE2     356333
CO9     129338
CO1      66760
RU1      63711
CO6      27260
PP3      26736
RE5      24844
IN       17705
CO5      13034
Name: count, dtype: int64

✓ Todos os CLAS_SUB foram mapeados com sucesso

--- Distribuição final por classe ---
_classe
residencial           4739419
comercial              246138
rural                   67831
poder_publico           30850
industrial              17705
iluminacao_publica       7314
servico_publico          4238
consumo_proprio           468
Name: count, dtype: int64

Total de UCs: 5,113,963

In [53]:
# %% [Célula 9b — Pivot: percentuais por classe e por alimentador]

# Pivot: linhas = CTMT, colunas = classe, valores = contagem de UCs
mix = ucbt_validas.pivot_table(
    index='CTMT',
    columns='_classe',
    values='COD_ID',
    aggfunc='count',
    fill_value=0
).reset_index()

# Calcula totais e percentuais
classes_presentes = [c for c in mix.columns if c != 'CTMT']
mix['_total'] = mix[classes_presentes].sum(axis=1)

for c in classes_presentes:
    mix[f'pct_{c}'] = (100 * mix[c] / mix['_total']).round(2)

# Remove a coluna temporária e organiza
mix = mix.drop(columns=['_total'])

# Mostra resumo
print(f"Mix calculado para {len(mix):,} alimentadores")
print(f"\nClasses identificadas: {classes_presentes}\n")

print("Estatísticas dos percentuais:")
cols_pct = [c for c in mix.columns if c.startswith('pct_')]
print(mix[cols_pct].describe().round(1))

print("\nAmostra (primeiras 5 linhas):")
display(mix.head())

Mix calculado para 1,532 alimentadores

Classes identificadas: ['comercial', 'consumo_proprio', 'iluminacao_publica', 'industrial', 'poder_publico', 'residencial', 'rural', 'servico_publico']

Estatísticas dos percentuais:
_classe  pct_comercial  pct_consumo_proprio  pct_iluminacao_publica  pct_industrial  pct_poder_publico  pct_residencial  pct_rural  pct_servico_publico
count          1532.00              1532.00                 1532.00         1532.00            1532.00          1532.00    1532.00              1532.00
mean              7.10                 0.10                    0.20            0.90               0.80            87.90       2.80                 0.10
std               9.80                 2.70                    0.40            4.00               1.70            15.50       9.40                 0.30
min               0.00                 0.00                    0.00            0.00               0.00             0.00       0.00                 0.00
25%               2.90                 0.00                    0.00            0.10               0.20            87.40       0.00                 0.00
50%               4.40                 0.00                    0.10            0.30               0.50            92.50       0.10                 0.00
75%               7.50                 0.00                    0.20            0.60               1.00            95.40       1.80                 0.10
max             100.00               100.00                    8.30          100.00              42.90           100.00     100.00                 5.90

Amostra (primeiras 5 linhas):

_classe,CTMT,comercial,consumo_proprio,iluminacao_publica,industrial,poder_publico,residencial,rural,servico_publico,pct_comercial,pct_consumo_proprio,pct_iluminacao_publica,pct_industrial,pct_poder_publico,pct_residencial,pct_rural,pct_servico_publico
0,ABR07,11,1,0,4,2,737,12,0,1.43,0.13,0.00,0.52,0.26,96.09,1.56,0.00
1,ABR08,105,1,4,14,37,5903,117,8,1.70,0.02,0.06,0.23,0.60,95.38,1.89,0.13
2,ABR09,268,0,8,13,60,5979,0,1,4.23,0.00,0.13,0.21,0.95,94.47,0.00,0.02
3,ABR10,90,0,2,30,6,2905,6,3,2.96,0.00,0.07,0.99,0.20,95.50,0.20,0.10
4,ABR11,34,0,3,6,12,3690,1,1,0.91,0.00,0.08,0.16,0.32,98.48,0.03,0.03

In [37]:
# %% [Célula 10] — Constrói DataFrame mestre da CTMT enriquecida
print("Construindo DataFrame mestre...\n")

# Começa do CTMT base (já tem ten_nom_kv da Célula 4b)
df = ctmt.copy()

# Renomeia colunas finais para clareza
df = df.rename(columns={
    'COD_ID': 'cod_id',
    'SUB': 'cod_sub',
})

# Junta comprimento
df = df.merge(comp_por_ctmt, left_on='cod_id', right_on='CTMT', how='left')
df = df.drop(columns=['CTMT'])
# Junta UCBT
df = df.merge(n_ucbt_por_ctmt, left_on='cod_id', right_on='CTMT', how='left')
df = df.drop(columns=['CTMT'])

# Junta UCMT
df = df.merge(n_ucmt_por_ctmt, left_on='cod_id', right_on='CTMT', how='left')
df = df.drop(columns=['CTMT'])

# Junta demanda
df = df.merge(demanda, left_on='cod_id', right_on='CTMT', how='left')
df = df.drop(columns=['CTMT'])

# Junta mix
df = df.merge(mix, left_on='cod_id', right_on='CTMT', how='left')
df = df.drop(columns=['CTMT'])

# Anota distribuidora
df['distribuidora'] = NOME_DIST

# Preenche NaN com 0 onde faz sentido
cols_zero = ['n_ucbt', 'n_ucmt', 'dem_med_ucbt_kw', 'dem_med_ucmt_kw',
             'dem_total_kw', 'comp_total_km', 'n_segmentos']
for c in cols_zero:
    if c in df.columns:
        df[c] = df[c].fillna(0)

# Calcula uma feature derivada útil: densidade de carga
df['densidade_kw_por_km'] = np.where(
    df['comp_total_km'] > 0,
    df['dem_total_kw'] / df['comp_total_km'],
    0
)

print(f"✓ DataFrame mestre construído: {len(df):,} alimentadores\n")
print("Colunas finais:")
print(df.columns.tolist())

Construindo DataFrame mestre...

✓ DataFrame mestre construído: 1,636 alimentadores

Colunas finais:
['cod_id', 'NOME', 'BARR', 'cod_sub', 'PAC_INI', 'TEN_NOM', 'TEN_OPE', 'ATIP', 'RECONFIG', 'DIST', 'UNI_TR_AT', 'ENE_01', 'ENE_02', 'ENE_03', 'ENE_04', 'ENE_05', 'ENE_06', 'ENE_07', 'ENE_08', 'ENE_09', 'ENE_10', 'ENE_11', 'ENE_12', 'PERD_A3a', 'PERD_A4', 'PERD_B', 'PERD_MED', 'PERD_A3aA4', 'PERD_A3a_B', 'PERD_A4A3a', 'PERD_A4_B', 'PERD_B_A3a', 'PERD_B_A4', 'PNTMT_01', 'PNTMT_02', 'PNTMT_03', 'PNTMT_04', 'PNTMT_05', 'PNTMT_06', 'PNTMT_07', 'PNTMT_08', 'PNTMT_09', 'PNTMT_10', 'PNTMT_11', 'PNTMT_12', 'PNTBT_01', 'PNTBT_02', 'PNTBT_03', 'PNTBT_04', 'PNTBT_05', 'PNTBT_06', 'PNTBT_07', 'PNTBT_08', 'PNTBT_09', 'PNTBT_10', 'PNTBT_11', 'PNTBT_12', 'DESCR', 'ten_nom_kv', 'comp_total_km', 'n_segmentos', 'n_ucbt', 'n_ucmt', 'dem_med_ucbt_kw', 'dem_med_ucmt_kw', 'dem_total_kw', 'outros', 'pct_outros', 'distribuidora', 'densidade_kw_por_km']

In [38]:
# %% [Célula 11] — Validação
print("=" * 70)
print("VALIDAÇÃO DO DATAFRAME MESTRE")
print("=" * 70)

# 1. Há alimentadores sem dados?
sem_geo = (df['comp_total_km'] == 0).sum()
sem_uc  = (df['n_ucbt'] + df['n_ucmt'] == 0).sum()
sem_dem = (df['dem_total_kw'] == 0).sum()

print(f"\nAlimentadores SEM geometria (km=0):    {sem_geo}/{len(df)}")
print(f"Alimentadores SEM consumidores:         {sem_uc}/{len(df)}")
print(f"Alimentadores SEM demanda calculada:    {sem_dem}/{len(df)}")

# 2. Estatísticas das colunas-chave
print("\n--- Estatísticas das colunas numéricas ---")
cols_num = ['ten_nom_kv', 'comp_total_km', 'n_ucbt', 'n_ucmt',
            'dem_total_kw', 'densidade_kw_por_km']
print(df[cols_num].describe().round(2))

# 3. Top 5 maiores e menores alimentadores por demanda
print("\n--- Top 5 MAIORES alimentadores (por demanda) ---")
display(df.nlargest(5, 'dem_total_kw')[
    ['cod_id', 'cod_sub', 'ten_nom_kv', 'comp_total_km', 'n_ucbt', 'dem_total_kw']
])

print("\n--- Top 5 MENORES alimentadores (por demanda, com dem>0) ---")
display(df[df['dem_total_kw'] > 0].nsmallest(5, 'dem_total_kw')[
    ['cod_id', 'cod_sub', 'ten_nom_kv', 'comp_total_km', 'n_ucbt', 'dem_total_kw']
])

======================================================================
VALIDAÇÃO DO DATAFRAME MESTRE
======================================================================

Alimentadores SEM geometria (km=0):    1/1636
Alimentadores SEM consumidores:         83/1636
Alimentadores SEM demanda calculada:    89/1636

--- Estatísticas das colunas numéricas ---
       ten_nom_kv  comp_total_km   n_ucbt  n_ucmt  dem_total_kw  densidade_kw_por_km
count     1636.00        1636.00  1636.00 1636.00       1636.00              1636.00
mean        12.87          55.51  3125.89   17.55       1954.25               129.00
std          2.94          85.44  2244.07   16.32       1121.18               450.49
min         11.40           0.00     0.00    0.00          0.00                 0.00
25%         11.40          10.91  1277.50    7.00       1257.98                19.44
50%         13.20          22.08  3034.50   14.00       1888.33                73.93
75%         13.80          64.98  4743.75   23.25       2595.35               135.77
max         45.00         979.86 14236.00  223.00       7257.69             15549.99

--- Top 5 MAIORES alimentadores (por demanda) ---

     cod_id cod_sub  ten_nom_kv  comp_total_km   n_ucbt  dem_total_kw
1435  PCA21     PCA       13.20          34.08 10712.00       7257.69
1059  HIP22     HIP       13.20          28.79  3537.00       7170.78
1388  VVT31     VVT       34.50         373.19  9089.00       6775.58
1105  NOD16     NOD       11.40           9.07   653.00       6557.46
1403  AUX33     AUX       34.50         970.40 12815.00       6406.67

--- Top 5 MENORES alimentadores (por demanda, com dem>0) ---

     cod_id cod_sub  ten_nom_kv  comp_total_km  n_ucbt  dem_total_kw
969   UES03     UES       13.20           0.07    1.00          0.56
1404  IVA11     IVA       13.80           1.08    0.00          0.94
545   KIB01     KIB       13.80           2.06    2.00          1.29
41    RIF22     RIF       13.80           1.37    8.00          2.19
951   TRM03     TRM       13.20           0.01    1.00          4.71